# Generated by Django 6.0.6 on 2026-07-05 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('engine_volume', models.IntegerField(help_text='Объём двигателя в см³')),
                ('power', models.IntegerField(blank=True, help_text='Мощность в л.с.', null=True)),
                ('moto_type', models.CharField(choices=[('sport', 'Спорт'), ('cruiser', 'Круизер'), ('enduro', 'Эндуро'), ('naked', 'Нейкед'), ('touring', 'Туристический')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='motos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycles', to='motos.brand')),
            ],
        ),
    ]
